version: '3'

services:
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network

  one-business:
    build:
      context: ./one-business
      dockerfile: Dockerfile
    environment:
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - eureka

networks:
  my-network:
    driver: bridge