spring:
  application:
    name: one-application
#  zipkin:
#    base-url: http://zipkin:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true