spring:
  application:
    name: two-application
#  zipkin:
#    base-url: http://zipkin:9411
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true